package gui.scene;

public enum SceneType {
    FORSIDE,
    LAGER,
    OPRETLAGER,
    REDIGERLAGER,
    DESTILLERING,
    OPRETDESTILLERING,
    REDIGERDESTILLERING,
    DESTILLERINGFAD,
    DESTILLERINGFLASKE,
    DESTILLERINGTANK,
    FAD,
    OPRETFAD,
    REDIGERFAD,
    GINFLASKE,
    OPRETGINFLASKE,
    REDIGERGINFLASKE,
    WHISKYFLASKE,
    OPRETWHISKYFLASKE,
    REDIGERWHISKYFLASKE,
    RÅVARE,
    OPRETRÅVARE,
    REDIGERRÅVARE,
    PLASTICTANK,
    OPRETPLASTICTANK,
    REDIGERPLASTICTANK
}
